## Load_Tokenization

In [6]:
import pandas as pd
import numpy as np
import re
import pickle

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

In [4]:
df = pd.read_csv('./data_l/ssodam2021_tokenized.csv',encoding='utf-8')

In [18]:
df.iloc[0]

num                                                                    1082901
board                                                                      익게2
title                                                                    해피뉴이어
text                                                      2021년은 모두 행복한 한해가 되길
writer                                                                      익명
upload_date                                                         2021/01/01
upload_time                                                              00:00
view                                                                    1343.0
likes                                                                    195.0
dislikes                                                                   0.0
comments                     앗, 성지다, 첫글 ㅊㅊ, 추천 준다, 내 24살은 인생에서 가장 빛나는 날로 만들...
comments_writer                                                            NaN
comments_cnt                                        

### Preprocessing

In [19]:
def get_noun_list_from_str(msg):
    try :
        return [tuple([re.sub("'",'',y) for y in re.findall('\'.*?\'',x)]) for x in re.findall('\(.*?\)',msg)]
    except :
        return np.NaN

In [20]:
df = df.fillna('')
df.text_tokenized = df.text_tokenized.apply(lambda x: get_noun_list_from_str(x))
df.title_tokenized = df.title_tokenized.apply(lambda x: get_noun_list_from_str(x))
df.comments_tokenized = df.comments_tokenized.apply(lambda x: get_noun_list_from_str(x))
df.comments_writer_tokenized = df.comments_writer_tokenized.apply(lambda x: get_noun_list_from_str(x))
df.upload_date = pd.to_datetime(df.upload_date)

In [82]:
df.head()

num board              title                  text writer upload_date  \
0  1082901   익게2              해피뉴이어  2021년은 모두 행복한 한해가 되길     익명  2021-01-01   
1  1082902   익게2   2021년 새해복 많이받으세요     모든 일이 잘 되기를 12시 땡     익명  2021-01-01   
2  1082903   익게2             첫글은 내꼬             예비회계사 나다미     익명  2021-01-01   
3  1082905   익게2           땡ㅎㅎㅎㅎㅎㅎㅎ                    1등     익명  2021-01-01   
4  1082906   익게2  어디 카운트 다운 하는 곳 없냐                  언제바껴     익명  2021-01-01   

  upload_time    view  likes  dislikes  \
0       00:00  1343.0  195.0       0.0   
1       00:00   107.0    3.0       0.0   
2       00:00   139.0    1.0       0.0   
3       00:00    39.0    0.0       0.0   
4       00:00    84.0    0.0       0.0   

                                            comments   comments_writer  \
0  앗, 성지다, 첫글 ㅊㅊ, 추천 준다, 내 24살은 인생에서 가장 빛나는 날로 만들...                     
1                                                늦었네  2빠다 ㅎㅎ, 내년에 도전한다   
2                                     ㄹㅇ 1등이네 ㅋㅋ, 실패                ㅜㅜ   
3                                                                        
4                                          232번 불교방송                     

   comments_cnt                                     text_tokenized  \
0          20.0  [(2021년, Number), (은, Foreign), (모두, Noun), (행...   
1           3.0  [(모든, Noun), (일이, Modifier), (잘, Verb), (되, Ve...   
2           3.0   [(예비, Noun), (회계사, Noun), (나, Noun), (다미, Noun)]   
3           0.0                                     [(1등, Number)]   
4           1.0             [(언, Modifier), (제바, Noun), (껴, Verb)]   

                                     title_tokenized  \
0                                    [(해피뉴이어, Noun)]   
1  [(2021년, Number), (새해, Noun), (복, Noun), (많이, ...   
2  [(첫, Modifier), (글, Noun), (은, Josa), (내꼬, Noun)]   
3             [(땡, Noun), (ㅎㅎㅎㅎㅎㅎㅎ, KoreanParticle)]   
4  [(어디, Noun), (카운트, Noun), (다운, Noun), (하는, Ver...   

                                  comments_tokenized  \
0  [(앗, Noun), (,, Punctuation), (성지, Noun), (다, ...   
1                                      [(늦었네, Verb)]   
2  [(ㄹㅇ, KoreanParticle), (1등, Number), (이네, Fore...   
3                                                 []   
4  [(232, Number), (번, Noun), (불교, Noun), (방송, No...   

                           comments_writer_tokenized  
0                                                 []  
1  [(2, Number), (빠다, Noun), (ㅎㅎ, KoreanParticle)...  
2                             [(ㅜㅜ, KoreanParticle)]  
3                                                 []  
4                                                 []

In [7]:
with open('./data_l/ssodam2021_tokenized_df.pkl','rb') as f:
    df = pickle.load(f)

## BoW

In [163]:
#불용어 load
with open('./data/stopwords.txt',encoding='utf-8') as f:
    stopwords = f.read().split()

In [370]:
#형태소 체크
limit = 0
for row in df.total_tokens:
    if limit > 10:
        break
    for tup in row:
        if tup[1]=='VerbPrefix':
            print(tup)
            limit += 1

('잘', 'VerbPrefix')
('안', 'VerbPrefix')
('안', 'VerbPrefix')
('못', 'VerbPrefix')
('잘', 'VerbPrefix')
('안', 'VerbPrefix')
('잘', 'VerbPrefix')
('안', 'VerbPrefix')
('안', 'VerbPrefix')
('안', 'VerbPrefix')
('안', 'VerbPrefix')
('잘', 'VerbPrefix')
('안', 'VerbPrefix')


### 익게2 데이터로부터 BoW 생성

In [585]:
#Total Token's Bag of Words
corpus = []
for column in ['total_tokens']:
    for text in df.loc[df['board']=='익게2',column]:
        for word in text:
            if word[1]=='Noun':
                if word[0] not in stopwords:
                    corpus.append(word[0])

In [593]:
idx_total = {}
bow_total = []

for token in corpus:
    if token not in idx_total.keys():
        idx_total[token] = len(idx_total)
        bow_total.insert(len(idx_total)-1,1)
    else:
        bow_total[idx_total[token]] += 1
        
idx_key = list(idx_total.keys())

In [10]:
with open('./data/idx_total.pkl','rb') as f:
    idx_total = pickle.load(f)
with open('./data/bow_total.pkl','rb') as f:
    bow_total = pickle.load(f)
idx_key = list(idx_total.keys())

### 익게2의 각 날짜별 BoW 생성

In [596]:
from datetime import datetime, timedelta

#corpus for each day
cfd = pd.DataFrame(columns=['upload_date','BoW'])

for date in date_range(datetime(2021,1,1), datetime(2021,7,1)):
    bow = np.zeros(len(idx_total.keys()))
    
    for token in df.loc[(df.board=='익게2') & (df.upload_date==date),'total_tokens']:
        for word in token:
            if (word[1]=='Noun') and (word[0] not in stopwords):
                try:
                    bow[idx_total[word[0]]] += 1
                except:
                    print('Error occured')
                    
    cfd.loc[len(cfd)] = [date, bow]

In [12]:
with open('./data_l/cfd.pkl','rb') as f:
    cfd = pickle.load(f)

In [15]:
#BoW 매트릭스
BoW_mat = np.array([list(value) for value in cfd.BoW.values])
BoW_mat

array([[11.,  1., 29., ...,  0.,  0.,  0.],
       [ 0.,  0., 41., ...,  0.,  0.,  0.],
       [ 2.,  3., 42., ...,  0.,  0.,  0.],
       ...,
       [ 3.,  1., 69., ...,  0.,  0.,  0.],
       [ 1.,  3., 53., ...,  0.,  0.,  0.],
       [ 1.,  3., 54., ...,  1.,  2.,  1.]])

### 날짜별 인기 키워드 탐색

#### 지수 정의

급상승 지수
1. 전일 언급 횟수 a
2. 당일 언급된 횟수 b
3. 전체 기간 중 언급 횟수 c
4. 가중치 w0, w1, w2
5. 적당한 상수 K, 아주 작은 상수 E

w0 x log(1+(b - a)/(a + K1)) + w1 x tanh( 0.1 x (b - K2) ) - w2 x c^E

In [16]:
def relu(x):
    if x<0:
        return 0
    else:
        return x

# [w0, w1, w2, K1, K2, E]    
W = [1,1,-0.0001,10,10,1.1]

def _hot_point(a,b,c):
    x0 = np.log(relu(((b-a)/(a+W[3])))+1)
    x1 = np.tanh(0.1*(b-W[4]))
    x2 = pow(c,W[5])
    
    return W[0]*x0, W[1]*x1, W[2]*x2
    
def hot_point(a,b,c):
    x,y,z = _hot_point(a,b,c)
    return x + y + z

def pp2(a,b,idx):
    c = BoW_mat[:,idx].sum()
    x, y, z = _hot_point(a,b,c)
    print(f'상승률지수 : {x}')
    print(f'언급지수   : {y}')
    print(f'패널티     : {z}')
    print(f'최종값     : {x+y+z}')

#### 날짜/단어별 지수 columns 생성

In [266]:
#각 날짜/단어별 급상승 지수 계산
cfd['points'] = [np.zeros(len(bow_total)) for i in range(len(cfd))]

for i in range(1,len(BoW_mat)):
    for j in range(len(bow_total)):
        cfd.points[i][j] = hot_point(BoW_mat[i-1,j],BoW_mat[i,j],BoW_mat[:,j].sum())

In [267]:
#Points 매트릭스
Points = np.array([list(value) for value in cfd.points.values])
Points

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.78060801, -0.77416411, -0.49338631, ..., -0.76169416,
        -0.76180851, -0.76169416],
       [-0.50072907, -0.35457346, -0.74149917, ..., -0.76169416,
        -0.76180851, -0.76169416],
       ...,
       [-0.36101737, -0.63355764, -0.33941053, ..., -0.76169416,
        -0.76180851, -0.76169416],
       [-0.73531173, -0.44988364, -0.7579678 , ..., -0.76169416,
        -0.76180851, -0.76169416],
       [-0.73531173, -0.61693773, -0.74215272, ..., -0.62108769,
        -0.48192957, -0.62108769]])

- __불용어 추가__

In [268]:
X_list = ['데','뭐','게','익','층','실','곤','급','관','쪽','번','중','감','명','점','곳']
for idx in [idx_total[key] for key in X_list]:
    Points[:,idx] = 0

#### 일별 상위 10, 20개 키워드 추려내기

In [269]:
#index 찾아 True로 저장할 ndarray 정의
top10s = np.zeros(Points.shape, dtype=bool)
top20s = np.zeros(Points.shape, dtype=bool)

for i in range(1,len(Points)):
    #날짜별 점수 상위 10개만 추림
    limit_10 = np.sort(Points[i,:])[-10]
    limit_20 = np.sort(Points[i,:])[-20]
    for j in range(Points.shape[1]):
        if Points[i,j]>=limit_20:
            #상위 20개에 대해 True값으로 저장
            top20s[i,j] = True
            
            if Points[i,j]>=limit_10:
                #상위 10개에 대해 True값으로 저장
                top10s[i,j] = True

top10s

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [270]:
#일별 상위 10개 키워드 저장
top10_keywords = [[idx_key[int(j)] for j in np.arange(top10s.shape[1])[top10s[i]]] for i in range(len(top10s))]
#일별 상위 20개 키워드 저장
top20_keywords = [[idx_key[int(j)] for j in np.arange(top20s.shape[1])[top20s[i]]] for i in range(len(top20s))]

In [271]:
top20_keywords[1]

['선택',
 '얘',
 '배려',
 '경험',
 '룸메',
 '족보',
 '생리',
 '대학원',
 '서로',
 '헬스장',
 '밑',
 '약',
 '조언',
 '중대',
 '연구',
 '김치',
 '냉동',
 '감염',
 '모닝콜',
 '쓰레기']

#### 상위 10개 키워드 중 빈출 키워드 찾기

__top10s__의 __BoW__ 생성

In [272]:
top10s_idx = {}
top10s_bow = []

for day_keywords in top10_keywords:
    for keyword in day_keywords:
        if keyword not in top10s_idx.keys():
            top10s_idx[keyword]=len(top10s_idx)
            top10s_bow.insert(len(top10s_idx)-1,1)
        else :
            top10s_bow[top10s_idx[keyword]]+=1
            
top10s_bow = np.array(top10s_bow)

__BoW__를 __DataFrame__화

In [273]:
top10s_keys = [key for key, value in top10s_idx.items()]

df_10bow = pd.DataFrame(np.array([top10s_keys,top10s_bow]).T,
                      columns = ['keyword','count'])
df_10bow['count'] = df_10bow['count'].astype(int)

df_10bow.head()

keyword  count
0      배려      1
1      룸메      1
2      생리      3
3     헬스장      1
4      조언      1

In [274]:
df_10bow.sort_values('count',ascending=False)[:50]

keyword  count
114      연애      8
420      외모      8
17      변호사      8
69       문과      8
577      아빠      7
33       일본      7
223      의사      7
65       의대      6
294      대출      6
64       중국      6
78       휴학      6
256     동아리      6
11       동생      6
50       세대      6
113      헌혈      6
6        냉동      6
257     고양이      6
218      논문      6
32       정치      5
149      생일      5
795      조교      5
45       과외      5
184      이과      5
265      교회      5
42       대면      5
62       애플      5
609      투표      5
326     경제학      5
168      언니      5
290      삼성      5
222      수술      5
357     할머니      5
772      오빠      5
14       검사      5
205      수능      5
504      리트      5
769      학부      5
336      소득      4
300      피자      4
534      백신      4
124      정원      4
337     예수회      4
310     서울대      4
279     진이뽀      4
125     장학금      4
68       공대      4
318      선수      4
90      로욜라      4
72      마스크      4
698      학벌      4

#### 상위 20개 키워드 중 빈출 키워드 찾기

__top20s__의 __BoW__ 생성

In [275]:
top20s_idx = {}
top20s_bow = []

for day_keywords in top20_keywords:
    for keyword in day_keywords:
        if keyword not in top20s_idx.keys():
            top20s_idx[keyword]=len(top20s_idx)
            top20s_bow.insert(len(top20s_idx)-1,1)
        else :
            top20s_bow[top20s_idx[keyword]]+=1
            
top20s_bow = np.array(top20s_bow)

__BoW__를 __DataFrame__화

In [276]:
top20s_keys = [key for key, value in top20s_idx.items()]

df_20bow = pd.DataFrame(np.array([top20s_keys,top20s_bow]).T,
                      columns = ['keyword','count'])
df_20bow['count'] = df_20bow['count'].astype(int)

df_20bow.head()

keyword  count
0      선택      3
1       얘      1
2      배려      2
3      경험      1
4      룸메      1

In [277]:
df_20bow.sort_values('count',ascending=False)[:50]

keyword  count
35       변호사     14
178       결혼     13
137       문과     12
40        휴학     12
271       아빠     12
70        외모     12
24        동생     12
220       연애     11
63        미국     11
518        팬     10
125       중국     10
448       학부     10
69        일본     10
703       총장     10
976        곡      9
408       병원      9
80        수능      9
509       조교      9
47        대면      9
107       철학      9
38        경찰      9
468      고양이      9
135       복전      9
206       합격      9
97        세대      8
122       애플      8
462      동아리      8
73        사건      8
133       공대      8
142       이과      8
147       담배      8
774       공감      8
402      경제학      8
333       논문      8
405       수술      8
118       주식      8
88        카페      8
296       축하      8
317       언니      8
36        의사      8
5         족보      8
1080      방송      7
880        키      7
26       부모님      7
464       오빠      7
207        형      7
30         폰      7
353       선배      7
75       부동산      7
1020      코인      7

__가중치 조정 기록 및 결과 저장__

In [278]:
'''
import pickle
f_idx = '2nd'
with open(f'{f_idx}_weights.pkl','wb') as f:
    pickle.dump(W,f)
with open(f'{f_idx}_cfd.pkl','wb') as f:
    pickle.dump(cfd,f)
with open(f'{f_idx}_10bow.pkl','wb') as f:
    pickle.dump(df_10bow,f)
with open(f'{f_idx}_20bow.pkl','wb') as f:
    pickle.dump(df_20bow,f)
'''

__불러오기__

In [14]:
with open('./data/10bow.pkl','rb') as f:
    df_10bow = pickle.load(f)
with open('./data/20bow.pkl','rb') as f:
    df_20bow = pickle.load(f)

---

## 월별 인기 키워드 찾기

### 작년 12월 데이터를 Load

In [27]:
tokens_20 = pd.read_csv('./data/ssodam2020_all_tokened_final.csv', encoding='utf-8')
#날짜 데이터를 datetime으로.
tokens_20.upload_date = pd.to_datetime(tokens_20.upload_date)
tokens_20.head()

num board         title     text writer upload_date upload_time  view  \
0  813032   익게2   2020년 파이팅!!  모두들 파이팅     익명  2020/01/01       00:00  1375   
1  813033   익게2            새해       ㅊㅊ     익명  2020/01/01       00:00    97   
2  813034   익게2  2020 첫 글 ㄱㅈㅇ       ㅇㅇ     익명  2020/01/01       00:00   128   
3  813037   익게2            ㅅㅅ       ㅅㅅ     익명  2020/01/01       00:00    70   
4  813038   익게2         스물넷이다  뭐했다고 벌써     익명  2020/01/01       00:00   124   

   likes  dislikes                                           comments  \
0    168         0  ['올 첫글 ㅋㅋ', '아 너 뭔데 나보다 일찍 썼냐ㅡㅡ추천이나 먹어라', '첫글 ...   
1      2         0                                                NaN   
2      1         0                                                NaN   
3      0         0                                                NaN   
4      3         0                         ['어? 너두?', '난방금전까지 스물넷..']   

  comments_writer  comments_cnt  popularity  \
0             NaN            14           1   
1             NaN             0           0   
2             NaN             0           0   
3             NaN             0           0   
4             NaN             2           0   

                                     text_tokenized  \
0                                 [('파이팅', 'Noun')]   
1                        [('ㅊㅊ', 'KoreanParticle')]   
2                        [('ㅇㅇ', 'KoreanParticle')]   
3                        [('ㅅㅅ', 'KoreanParticle')]   
4  [('뭐', 'Noun'), ('했다고', 'Verb'), ('벌써', 'Noun')]   

                                     title_tokenized  \
0  [('2020년', 'Number'), ('파이팅', 'Noun'), ('!!', ...   
1                                   [('새해', 'Noun')]   
2  [('2020', 'Number'), ('첫', 'Noun'), ('글', 'Nou...   
3                         [('ㅅㅅ', 'KoreanParticle')]   
4                  [('스물넷', 'Noun'), ('이다', 'Josa')]   

                                   comment_tokenized  
0  [("['", 'Punctuation'), ('올', 'Verb'), ('첫', '...  
1                                                NaN  
2                                                NaN  
3                                                NaN  
4  [("['", 'Punctuation'), ('?', 'Punctuation'), ...

In [39]:
def get_noun_list_from_str(msg):
    try :
        return [tuple([re.sub("'",'',y) for y in re.findall('\'.*?\'',x)]) for x in re.findall('\(.*?\)',msg)]
    except :
        return np.NaN

In [69]:
#12월 데이터만 추려내어 처리
tokens_20_12 = tokens_20[tokens_20.upload_date.apply(lambda x: True if x.month==12 else False)]
tokens_20_12 = tokens_20_12.fillna('')
tokens_20_12.text_tokenized = tokens_20_12.text_tokenized.apply(lambda x: get_noun_list_from_str(x))
tokens_20_12.title_tokenized = tokens_20_12.title_tokenized.apply(lambda x: get_noun_list_from_str(x))
tokens_20_12.comment_tokenized = tokens_20_12.comment_tokenized.apply(lambda x: get_noun_list_from_str(x))
tokens_20_12['comments_writer_tokenized'] = [[] for _ in range(len(tokens_20_12))]
tokens_20_12.rename(columns={'comment_tokenized':'comments_tokenized'},inplace=True)
tokens_20_12.head()

num board                               title  \
161968  1058725   익게2                             엽기붕어빵ㅋㅋ   
161969  1058727   익게2                       다미들 푸우욱 잘 자라옹   
161970  1058728   익게2                         나 시 써봤는데 어때   
161971  1058729   익게2  민법 한번 공부해 보고싶은데.. 인강 뭐 들어야할지 모르겠어ㅜ   
161972  1058730   익게2             가정내에서도 결국 사회생활하듯이 살아야할까   

                                                     text writer upload_date  \
161968  붕어빵10개 1만 6천원ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ...     익명  2020-12-01   
161969                                               졸리다냥     익명  2020-12-01   
161970  거울 속에 한 사내가 서있다사내는 거울 속 자신의 모습이 볼품없다사내는 그런 자신의...     익명  2020-12-01   
161971  세무사 민법이랑                                법무사 민법...     익명  2020-12-01   
161972  나는 엄마랑 감정적으로 친해지고 싶지 않아말하는 관점이 너어어어무 다르고 남 험담을...     익명  2020-12-01   

       upload_time  view  likes  dislikes  \
161968       00:06   124      0         0   
161969       00:07   143      7         0   
161970       00:08   245      7         0   
161971       00:09   221      0         2   
161972       00:10   376     11         0   

                                                 comments  \
161968                              ['ㅈ같은 프리미엄화 좀 하지마라ㅠ']   
161969                                                      
161970  ['거사사 너때 때멈 살그... 라고요???? 말이 너무 심하시네요!! 비추드립니다...   
161971  ['로스쿨 민법 어때? - 로스쿨다미', '자기계발용으로는 적합한지 모르겠지만ㅋㅋㅋ...   
161972  ['솔직히 내가 그 상황이 아니니까 답은 알 수 없지만, 나라면 안 드려 이번에 드...   

                                          comments_writer  comments_cnt  \
161968                                                                1   
161969                                                                0   
161970  ['뭐라는거야ㅋㅋㅋㅋ', '저도 쓰고보니 이상 거울이랑 윤동주 자화상이랑 살짝 섞인...             8   
161971         ['헤헤 그거 들어볼까?? 혹시 추천 강사님 물어봐도돼?ㅎ', 'ㅋㅋㅋㅋ']             8   
161972  ['진짜 고민이야 ㅠㅠ 정말 오늘 아침도 또 아빠욕하길래 못들어주겟다고 하고 나왔는...            11   

        popularity                                     text_tokenized  \
161968           0  [(붕어빵, Noun), (10, Number), (개, Noun), (1만, Nu...   
161969           0                                     [(졸리다냥, Verb)]   
161970           0  [(거울, Noun), (속, Noun), (사내, Noun), (서있다, Verb...   
161971           0  [(세무사, Noun), (민법, Noun), (법무사, Noun), (민법, No...   
161972           0  [(엄마, Noun), (랑, Josa), (감정, Noun), (적, Suffix...   

                                          title_tokenized  \
161968    [(엽기, Noun), (붕어빵, Noun), (ㅋㅋ, KoreanParticle)]   
161969     [(푸우, Noun), (욱, Noun), (자라, Noun), (옹, Noun)]   
161970                [(시, Noun), (써, Verb), (봤는데, Verb)]   
161971  [(민법, Noun), (한번, Noun), (공부, Noun), (해, Verb)...   
161972  [(가정, Noun), (내, Noun), (에서도, Josa), (사회생활, No...   

                                       comments_tokenized  \
161968  [(", ,), (ㅈ, KoreanParticle), (같은, Adjective),...   
161969                                                 []   
161970  [(", ,), (사사, Noun), (때멈, Noun), (살그, Noun), (...   
161971  [(", ,), (로스쿨, Noun), (민법, Noun), (?, Punctuat...   
161972  [(", ,), (솔직히, Adjective), (내, Noun), (상황, Nou...   

       comments_writer_tokenized  
161968                        []  
161969                        []  
161970                        []  
161971                        []  
161972                        []

In [72]:
tokens_20_12.columns

Index(['num', 'board', 'title', 'text', 'writer', 'upload_date', 'upload_time',
       'view', 'likes', 'dislikes', 'comments', 'comments_writer',
       'comments_cnt', 'popularity', 'text_tokenized', 'title_tokenized',
       'comments_tokenized', 'comments_writer_tokenized'],
      dtype='object')

In [73]:
df.columns

Index(['num', 'board', 'title', 'text', 'writer', 'upload_date', 'upload_time',
       'view', 'likes', 'dislikes', 'comments', 'comments_writer',
       'comments_cnt', 'text_tokenized', 'title_tokenized',
       'comments_tokenized', 'comments_writer_tokenized'],
      dtype='object')

In [84]:
df2 = pd.concat([tokens_20_12,df])

### 익게2 12월~6월간 BoW 생성

전체 데이터프레임을 월별로 groupby.

In [75]:
cfm_dict = dict.fromkeys(['upload_month','title_tokenized','text_tokenized','comments_tokenized','comments_writer_tokenized'])

for key in cfm_dict.keys():
    if key == 'upload_month':
        cfm_dict[key] = [12]+[i+1 for i in range(6)]
    else:
        cfm_dict[key] = [[] for i in range(7)]

cfm_dict

{'upload_month': [12, 1, 2, 3, 4, 5, 6],
 'title_tokenized': [[], [], [], [], [], [], []],
 'text_tokenized': [[], [], [], [], [], [], []],
 'comments_tokenized': [[], [], [], [], [], [], []],
 'comments_writer_tokenized': [[], [], [], [], [], [], []]}

In [658]:
_df = df2.loc[df2.board=='익게2']

for idx in range(len(_df)):
    if (idx+1)%10000==0:
        print('index :',idx,'processing...')
    row = _df.iloc[idx]
    #데이터프레임으로부터 월 인덱스 탐색
    month = 0 if row.upload_date.month==12 else row.upload_date.month
    #칼럼별 해당 인덱스에 해당되는 토큰 저장
    #50단어가 넘는 장문의 글은 제거하고 댓글과 제목만 남김.
    if len(row.text_tokenized) > 50:
        pass
    else :
        cfm_dict['text_tokenized'][month] += row.text_tokenized
    cfm_dict['title_tokenized'][month] += row.title_tokenized
    cfm_dict['comments_tokenized'][month] += row.comments_tokenized
    cfm_dict['comments_writer_tokenized'][month] += row.comments_writer_tokenized

index : 9999 processing...
index : 19999 processing...
index : 29999 processing...
index : 39999 processing...
index : 49999 processing...
index : 59999 processing...
index : 69999 processing...


In [659]:
cfm = pd.DataFrame(cfm_dict)
cfm['total_tokens'] = cfm.title_tokenized + cfm.text_tokenized + cfm.comments_tokenized + cfm.comments_writer_tokenized
cfm

upload_month                                    title_tokenized  \
0            12  [(엽기, Noun), (붕어빵, Noun), (ㅋㅋ, KoreanParticle)...   
1             1  [(해피뉴이어, Noun), (2021년, Number), (새해, Noun), (...   
2             2  [(않이, Verb), (모해, Noun), (따고, Verb), (벌써, Noun...   
3             3  [(약, Noun), (19, Number), (저가, Noun), (코스프레, N...   
4             4  [(만우절, Noun), (이, Josa), (벌써, Noun), (끝나, Verb...   
5             5  [(2021년, Number), (5월, Number), (첫, Noun), (글,...   
6             6  [(지금, Noun), (퇴근, Noun), (하는, Verb), (길, Noun)...   

                                      text_tokenized  \
0  [(붕어빵, Noun), (10, Number), (개, Noun), (1만, Nu...   
1  [(2021년, Number), (은, Foreign), (모두, Noun), (행...   
2  [(2월, Number), (이냐, Foreign), (지인, Noun), (이, ...   
3  [(취미, Noun), (로, Josa), (배워, Verb), (보고싶어, Ver...   
4  [(아쉽다, Adjective), (아쉬워, Adjective), (연애, Noun...   
5  [(새로운, Adjective), (달도, Noun), (희망, Noun), (차게...   
6  [(입사, Noun), (1년, Number), (아직, Adverb), (안된, ...   

                                  comments_tokenized  \
0  [(", ,), (ㅈ, KoreanParticle), (같은, Adjective),...   
1  [(앗, Noun), (,, Punctuation), (성지, Noun), (다, ...   
2  [(난, Noun), (마카롱, Noun), (세트, Noun), (했아, Verb...   
3  [(진짜, Noun), (이형, Noun), (꾸준하네, Adjective), (,...   
4  [(스타트, Noun), (가, Josa), (좋구만, Adjective), (ㄱㄱ...   
5  [(뭔, Modifier), (데, Noun), (벌써, Noun), (5월, Nu...   
6  [(화이팅, Noun), (시간, Noun), (이, Josa), (지나면, Ver...   

                           comments_writer_tokenized  \
0                                                 []   
1  [(2, Number), (빠다, Noun), (ㅎㅎ, KoreanParticle)...   
2  [(오, Noun), (좋다, Adjective), (고마워, Adjective),...   
3  [(고마워, Adjective), (덕분, Noun), (에, Josa), (등업,...   
4  [(나, Noun), (에게, Josa), (있다고, Adjective), (,, ...   
5  [(아, Exclamation), (진짜, Noun), (로, Josa), (그럼,...   
6  [(전망, Noun), (좋고, Adjective), (과제, Noun), (하기,...   

                                        total_tokens  
0  [(엽기, Noun), (붕어빵, Noun), (ㅋㅋ, KoreanParticle)...  
1  [(해피뉴이어, Noun), (2021년, Number), (새해, Noun), (...  
2  [(않이, Verb), (모해, Noun), (따고, Verb), (벌써, Noun...  
3  [(약, Noun), (19, Number), (저가, Noun), (코스프레, N...  
4  [(만우절, Noun), (이, Josa), (벌써, Noun), (끝나, Verb...  
5  [(2021년, Number), (5월, Number), (첫, Noun), (글,...  
6  [(지금, Noun), (퇴근, Noun), (하는, Verb), (길, Noun)...

In [660]:
#Total Token's Bag of Words
corpus_extended = []
for column in ['total_tokens']:
    for text in cfm[column]:
        for word in text:
            try:
                if word[1]=='Noun':
                    if word[0] not in stopwords:
                        corpus_extended.append(word[0])
            except:
                pass

In [661]:
idx_extended = {}
bow_extended = []

for token in corpus_extended:
    if token not in idx_extended.keys():
        idx_extended[token] = len(idx_extended)
        bow_extended.insert(len(idx_extended)-1,1)
    else:
        bow_extended[idx_extended[token]] += 1
        
idx_extended_key = list(idx_extended.keys())

In [664]:
'''
with open('./data/idx_extended.pkl','wb') as f:
    pickle.dump(idx_extended,f)
with open('./data/bow_extended.pkl','wb') as f:
    pickle.dump(bow_extended,f)
'''
with open('./data/idx_extended.pkl','rb') as f:
    idx_extended = pickle.load(f)
with open('./data/bow_extended.pkl','rb') as f:
    bow_extended = pickle.load(f)
idx_extended_key = list(idx_extended.keys())

"\nwith open('./data/idx_extended.pkl','rb') as f:\n    idx_extended = pickle.load(f)\nwith open('./data/bow_extended.pkl','rb') as f:\n    bow_extended = pickle.load(f)\nidx_extended_key = list(idx_extended.keys())\n"

###  Word별 게시글 수 탐색

In [983]:
def return_words(x):
    output = []
    for token in x:
        if len(token)>1:
            output.append(token[0])
        else:
            pass
    return output

df2['total_tokens'] = df2.title_tokenized + df2.text_tokenized + df2.comments_tokenized + df2.comments_writer_tokenized
df2['_total_tokens'] = df2['total_tokens'].apply(lambda x : return_words(x))

In [1554]:
from datetime import datetime
month_filter = []
for i in range(7):
    if i==0:
        month_filter.append((datetime(2020,12,1)<=df2.upload_date) & (df2.upload_date<datetime(2021,1,1)) & (df2.board=='익게2'))
    else:
        month_filter.append((datetime(2021,i,1)<=df2.upload_date) & (df2.upload_date<datetime(2021,i+1,1)) & (df2.board=='익게2'))

In [1016]:
import time
time.time()

1628994322.1614735

import time

posts_extended = np.zeros((7,len(idx_extended)))

start_time = time.time()

for i, word in enumerate(idx_extended):
    if i%1000 == 0:
        print(i,'번째 단어 처리중...',i-1000,'번째로부터',time.time()-start_time,'초 경과.')
        start_time = time.time()
    _all_posts = df2._total_tokens.apply(lambda x: True if word in x else False)
    for j in range(0,7):
        posts_extended[j,i] = _all_posts[month_filter[j]].sum()

In [8]:
with open('./data/posts_extended.pkl','rb') as f:
    posts_extended = pickle.load(f)

### 익게2 데이터로부터 월별 BoW 생성

__BoW 생성__

In [665]:
bows = []

for month in range(7):
    bow = np.zeros(len(idx_extended.keys()))
    
    for word in cfm.iloc[month].total_tokens:
        #()등 빈 단어들은 패스
        if len(word)!=2:
            continue
        if (word[1]=='Noun') and (word[0] not in stopwords):
            try:
                bow[idx_extended[word[0]]] += 1
            except:
                print('Error occured')
                
    bows.append(bow)

cfm['BoW'] = bows

In [668]:
'''
with open('./data_l/cfm.pkl','wb') as f:
    pickle.dump(cfm,f)
'''
with open('./data_l/cfm.pkl','rb') as f:
    cfm = pickle.load(f)

"\nwith open('./data/cfm.pkl','rb') as f:\n    cfm = pickle.load(f)\n"

### 급상승 지수 계산

idx_total & bow_total로부터 각 월마다 키워드별 급상승지수 계산

월별 급상승 지수
1. 전월 언급 횟수 a
2. 당월 언급된 횟수 b
3. 당월 게시글 작성 횟수 c
4. 전체 기간(2020.12~2021.6) 중 언급 횟수 d
5. 가중치 w0, w1, w2
6. 적당한 상수 K, 아주 작은 상수 E

w0 x log(1+(b - a)/(a + K1)) + w1 x tanh( 0.1 x (b - K2) ) - w2 x c^E

- 월별 등장 횟수는 일별 등장 횟수에 비해 양에 대한 기준치를 높여야 하므로, K1과 K2를 상향 조정

In [1021]:
posts_extended

array([[ 6., 16.,  1., ...,  0.,  0.,  0.],
       [ 4.,  6.,  1., ...,  0.,  0.,  0.],
       [ 2.,  2.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 1.,  5.,  3., ...,  0.,  0.,  0.],
       [ 9.,  6.,  1., ...,  0.,  0.,  0.],
       [ 3.,  6.,  1., ...,  1.,  1.,  1.]])

In [1027]:
BoW_mat

array([[ 36., 194.,   6., ...,   0.,   0.,   0.],
       [ 18.,  29.,   4., ...,   0.,   0.,   0.],
       [  4.,  20.,   0., ...,   0.,   0.,   0.],
       ...,
       [  3.,  38.,   8., ...,   0.,   0.,   0.],
       [ 22.,  18.,   3., ...,   0.,   0.,   0.],
       [ 12.,  39.,   3., ...,   3.,   3.,   3.]])

In [1500]:
def relu(x):
    if x<0:
        return 0
    else:
        return x
    
def sigmoid2(x):
    return 1/( 1+np.exp( -(x-5) ) )

#   [w0, w1, w2,  w3,  K1,  K2,   E]    
W = [1, 0.3, 0.6, -0.05, 10, 100, 1.002]

def _hot_point3(a,b,c,d,e):
    x0 = sigmoid2( ((b-a)/(a+W[4])) + 0.3*((d-c)/(c+W[4]/2)) )
    x1 = np.tanh(0.02*(b-W[5]))
    x2 = np.tanh(0.1*(d-20))-0.5
    x3 = pow(W[6],e) - 1
    
    return W[0]*x0, W[1]*x1, W[2]*x2, W[3]*x3
    
def hot_point3(a,b,c,d,e):
    x,y,z,w = _hot_point3(a,b,c,d,e)
    return x + y + z + w

def pp3(a,b,c,d,idx):
    e = BoW_mat[:,idx].sum()
    x, y, z, w = _hot_point3(a,b,c,d,e)
    print(f'상승률지수 : {x}')
    print(f'언급지수   : {y}')
    print(f'게시글수   : {z}')
    print(f'패널티     : {w}')
    print(f'최종값     : {x+y+z+w}')

In [1501]:
#BoW 매트릭스
BoW_mat = np.array([list(value) for value in cfm.BoW.values])
BoW_mat

array([[ 36., 194.,   6., ...,   0.,   0.,   0.],
       [ 18.,  29.,   4., ...,   0.,   0.,   0.],
       [  4.,  20.,   0., ...,   0.,   0.,   0.],
       ...,
       [  3.,  38.,   8., ...,   0.,   0.,   0.],
       [ 22.,  18.,   3., ...,   0.,   0.,   0.],
       [ 12.,  39.,   3., ...,   3.,   3.,   3.]])

In [1502]:
#각 날짜/단어별 급상승 지수 계산
cfm['points'] = [np.zeros(len(bow_extended)) for i in range(len(cfm))]

for i in range(1,len(BoW_mat)):
    for j in range(len(bow_extended)):
        cfm.points[i][j] = hot_point3(BoW_mat[i-1,j],BoW_mat[i,j],
                                      posts_extended[i-1,j],posts_extended[i,j],
                                      BoW_mat[:,j].sum())

In [1503]:
#Points 매트릭스
Points = np.array([list(value) for value in cfm.points.values])
Points

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.13824968, -1.15042475, -1.15872123, ..., -1.16123257,
        -1.16123257, -1.16123257],
       [-1.16295257, -1.19473933, -1.16634607, ..., -1.16123257,
        -1.16123257, -1.16123257],
       ...,
       [-1.16782914, -1.14450623, -1.14367514, ..., -1.16123257,
        -1.16123257, -1.16123257],
       [-1.02467963, -1.15982521, -1.16040464, ..., -1.16123257,
        -1.16123257, -1.16123257],
       [-1.15098264, -1.12397241, -1.15842446, ..., -1.15233796,
        -1.15233796, -1.15233796]])

__추가 불용어 정의__

In [1541]:
#도배된 단어 등 제외
for x_word in ['는','걍','을해','얀','인데','꿀꿀','끝내','쿠','원','쿠나']:
    Points[:,idx_extended[x_word]] = 0.

### 상위 키워드 추리기

In [1542]:
#index 찾아 True로 저장할 ndarray 정의
top10s = np.zeros(Points.shape, dtype=bool)
top20s = np.zeros(Points.shape, dtype=bool)

for i in range(1,len(Points)):
    #날짜별 점수 상위 10개만 추림
    limit_10 = np.sort(Points[i,:])[-10]
    limit_20 = np.sort(Points[i,:])[-20]
    for j in range(Points.shape[1]):
        if Points[i,j]>=limit_20:
            #상위 20개에 대해 True값으로 저장
            top20s[i,j] = True
            
            if Points[i,j]>=limit_10:
                #상위 10개에 대해 True값으로 저장
                top10s[i,j] = True

top10s

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [1543]:
#일별 상위 10개 키워드 저장
top10_keywords = [[idx_extended_key[int(j)] for j in np.arange(top10s.shape[1])[top10s[i]]] for i in range(len(top10s))]
#일별 상위 20개 키워드 저장
top20_keywords = [[idx_extended_key[int(j)] for j in np.arange(top20s.shape[1])[top20s[i]]] for i in range(len(top20s))]

In [1544]:
top10_keywords

[[],
 ['연말정산', '공모전', '눈사람', '능검', '개미', '공공기관', '페스', '페이크', '로토', '팬픽'],
 ['학보', '증원', '쿼터', '뻔뻔', '사인', '뻔선', '연휴', '뻔후', '폭로', '학교폭력'],
 ['피셋', '에이프릴', '결석', '로나', '검찰', '신도시', '투기', '롤린', '단태', '브레이브걸스'],
 ['파상', '벼락치기', '클로즈', '슈퍼리그', '비제', '너비', '애정', '만우절', '서예지', '김정현'],
 ['코난', '참가자', '퇴소', '사물함', '자진', '정민', '퍼즐', '이루리', '공혁준', '또즐'],
 ['부정행위', '텀페', '독일', '사프컴', '관회', '메리트', '광학', '팬덤', '유로', '소희']]

In [1545]:
top20_keywords

[[],
 ['소비자',
  '해커스',
  '연말정산',
  '공모전',
  '수료',
  '눈사람',
  '능검',
  '개미',
  '유의',
  '사지',
  '금리',
  '실적',
  '공공기관',
  '재래시장',
  '페스',
  '페이크',
  '정인',
  '로토',
  '팬픽',
  '강민철'],
 ['학보',
  '증원',
  '물성',
  '졸업식',
  '전공자',
  '분반',
  '쿼터',
  '설날',
  '뻔뻔',
  '실라',
  '사인',
  '괴롭힘',
  '명절',
  '뻔선',
  '연휴',
  '뻔후',
  '폭로',
  '학폭',
  '학교폭력',
  '탈세'],
 ['동선',
  '장관',
  '피셋',
  '에이프릴',
  '결석',
  '벚꽃',
  '수련',
  '로나',
  '검찰',
  '역주행',
  '토지',
  '신도시',
  '서진',
  '등업',
  '투기',
  '롤린',
  '단태',
  '브레이브걸스',
  '마사',
  '하윤'],
 ['파상',
  '벼락치기',
  '테뱅',
  '중도',
  '클로즈',
  '추대',
  '분포',
  '슈퍼리그',
  '시험지',
  '비제',
  '너비',
  '탭',
  '간담',
  '애정',
  '작',
  '권혁',
  '만우절',
  '도지',
  '서예지',
  '김정현'],
 ['코난',
  '범인',
  '전기',
  '참가자',
  '학생회',
  '퇴소',
  '무죄',
  '사물함',
  '실종',
  '자진',
  '파이',
  '어린이',
  '에어컨',
  '정민',
  '퍼즐',
  '이루리',
  '어버이날',
  '공혁준',
  '또즐',
  '니갸르'],
 ['부정행위',
  '경통',
  '열역학',
  '텀페',
  '중회',
  '미적분',
  '떡밥',
  '독일',
  '사프컴',
  '관회',
  '미분',
  '대리',
  '몸매',
  '메리트',
  '광학',
  '팬덤',
  '유로',
  '에고'

__월별 키워드 보기__

In [1546]:
month = 1

[(idx_extended_key[arg],Points[month,arg]) for arg in np.flip(np.argsort(Points[month])) if Points[month,arg]>0.4]

[('눈사람', 1.4388274350075867),
 ('페스', 1.372140387572578),
 ('능검', 1.2968763878230196),
 ('로토', 0.8801678698878485),
 ('페이크', 0.7076259121220817),
 ('팬픽', 0.5900550949301291),
 ('연말정산', 0.5843983551276155),
 ('개미', 0.4655224703512738),
 ('공공기관', 0.45791040726232746),
 ('공모전', 0.448157235581588),
 ('수료', 0.4420610743976951),
 ('금리', 0.4391737496845761),
 ('소비자', 0.4331361420301114),
 ('실적', 0.4265524576852504),
 ('해커스', 0.4249429654020079),
 ('강민철', 0.42325984109543124),
 ('유의', 0.41582487531914836),
 ('사지', 0.41059350647106896),
 ('정인', 0.4054266187954222),
 ('재래시장', 0.40193374821517885)]

### 단어별 검토

In [1548]:
_word = '공공기관'

- 월별 점수

In [1549]:
Points[:,idx_extended[_word]]

array([ 0.        ,  0.45791041, -0.33855227, -0.54824645, -0.93025855,
       -0.17494321, -0.6812255 ])

- 전체 등장 횟수

In [1550]:
bow_extended[idx_extended[_word]]

469

- 월별 등장 횟수

In [1551]:
BoW_mat[:,idx_extended[_word]]

array([ 81., 153.,  62.,  47.,  17.,  68.,  41.])

- 월별 게시글 수

In [1552]:
posts_extended[:,idx_extended[_word]]

array([45., 42., 24., 21., 15., 26., 19.])

- 지수 확인

In [1536]:
_word = '쿠나'

In [1553]:
end = 1
pp3(BoW_mat[end-1,idx_extended[_word]],BoW_mat[end,idx_extended[_word]],
    posts_extended[end-1,idx_extended[_word]], posts_extended[end,idx_extended[_word]],
    idx_extended[_word])

상승률지수 : 0.014389092450465357
언급지수   : 0.23569915770808308
게시글수   : 0.2854458780188709
패널티     : -0.07762372091509183
최종값     : 0.45791040726232746


- 내용 검색 툴

In [951]:
def search_cd(word, x):
    try:
        return True if word in [y[0] for y in x] else False
    except:
        return False

def s_search(word, month, show_urls=True):
    df_month = df2[df2.upload_date.apply(lambda x: True if x.month==month else False)]
    title_cd = df2.title_tokenized.apply(lambda x: search_cd(word,x))
    text_cd = df2.text_tokenized.apply(lambda x: search_cd(word,x))
    comments_cd = df2.comments_tokenized.apply(lambda x: search_cd(word,x))
    comments_writer_cd = df2.comments_writer_tokenized.apply(lambda x: search_cd(word,x))
    df = df_month[title_cd | text_cd | comments_cd | comments_writer_cd]
    if show_urls==True:
        [print('http://www.ssodam.com/content/'+str(number)) for number in df.num]
    return df

def numofposts(word, month):
    df = s_search(word,month,show_urls=False)
    return len(df)

In [1547]:
s_search('공공기관',1)

http://www.ssodam.com/content/1083036
http://www.ssodam.com/content/1083670
http://www.ssodam.com/content/1084556
http://www.ssodam.com/content/1085597
http://www.ssodam.com/content/1086277
http://www.ssodam.com/content/1086384
http://www.ssodam.com/content/1086874
http://www.ssodam.com/content/1087738
http://www.ssodam.com/content/1087918
http://www.ssodam.com/content/1088090
http://www.ssodam.com/content/1088234
http://www.ssodam.com/content/1088256
http://www.ssodam.com/content/1088296
http://www.ssodam.com/content/1089231
http://www.ssodam.com/content/1089673
http://www.ssodam.com/content/1090305
http://www.ssodam.com/content/1090471
http://www.ssodam.com/content/1090747
http://www.ssodam.com/content/1091235
http://www.ssodam.com/content/1091514
http://www.ssodam.com/content/1091547
http://www.ssodam.com/content/1091991
http://www.ssodam.com/content/1092521
http://www.ssodam.com/content/1092998
http://www.ssodam.com/content/1093426
http://www.ssodam.com/content/1093507
http://www.s

num  board                                  title  \
101    1083036  취업게시판                 공공기관 아르바이트와 교내근로 고민입니다   
550    1083670  취업게시판                수습기간에 코로나 걸리면 짤릴 수도 있나요   
1134   1084556  취업게시판                     채용전환인턴 시 네일아트나 피어싱   
1871   1085597  취업게시판                     이번에 서강대학교 장학부서직원채용   
2347   1086277  취업게시판                공기업 취업 희망시 사기업 인턴 영향 문의   
2412   1086384    익게2                            재택근무가 불공정한가   
2750   1086874    익게2                 리메이크 웹툰의 저작권에 대한 질문이에요   
3364   1087738    익게2                다음 시즌에는 얼어붙은 채용시장 좀 풀릴까   
3496   1087918    익게2              동생이 시 공모전에 응모했는데 돌아가는 상황이   
3606   1088090    익게2                               다들 재택근무해   
3697   1088234    익게2                            살기 ㅈㄴ빡세네 ㅋㅋ   
3713   1088256  취업게시판                         공대분들 조언 부탁드립니다   
3739   1088296    익게2                  나한테 잘 맞는 직업 모 잇을까추천해줘   
4400   1089231    익게2                   공무원 사회에서 시보떡 문화가 있다매   
4682   1089673    익게2                             한능검 마감 실화냐   
5077   1090305    익게2                          대기업 업무강도 궁금하다   
5170   1090471  취업게시판                            조언 부탁드립니다ㅠㅠ   
5357   1090747  취업게시판                               인사 직무 준비   
5646   1091235  취업게시판             서보보, 공공기관, 전공 시험 보는 곳 준비방법   
5831   1091514    익게2                 인구학자가 예측하는 미래의 한국 집값ㄷㄷ   
5851   1091547    익게2                     서울에 쏠리는 이유가 직장때문이지   
6132   1091991  취업게시판                   하 선배님들께 사회생활 조언 구합니다   
6495   1092521    익게2                     전통시장에서 음식 안 사먹는 이유   
6827   1092998    익게2           넷마블 자회사 내부 공지문으로 넷이랑 블라인드 터짐   
7123   1093426    익게2               오늘부터 공공기관 채용정보박람회 개최됨122   
7187   1093507    익게2                          시립대는 아예 전략을 좀   
7269   1093619    익게2                공공기관 인턴하면서 공모전 해도 문제 없지   
7464   1093902  취업게시판                           체험형 인턴 면접 복장   
7536   1094009    익게2                         그냥 안온하게 살고 싶으면   
7666   1094214    익게2                                 나 승진했어   
7702   1094268    익게2                               은행원이랑 싸움   
8222   1095024    익게2             공공기관에 궁금한거 문의 많이 해 본 다미 있니   
8342   1095217   채용정보     공공기관 한국저작권위원회 2021년 상반기 직원 채용 0104   
8395   1095290    익게2                     주임이 중소기업에만 있는 직함이야   
8667   1095691    익게2          우리학교도 공공기관 준비생 많이 는 걸로 알고 있는데   
8687   1095723    익게2                    사실 이제 20대의 90프로 이상이   
9836   1097382    CPA            금융공기업 가도  있으면 더 안정감 들지 않을까요   
10507  1098348    로스쿨            3년간 로스쿨 생활10기을 마치며 로스쿨생활 후기   
11010  1099119  취업게시판        무지주의 신입 월급 세후 현금300만원이면 많은 편인가요   
11142  1099319  취업게시판               나이랑 상관없이 지원할 수 있는 곳 있을까요   
11193  1099396    익게2                         26살 직장인 남다미 무물   
11218  1099436  취업게시판  일반공기업에서 금융공기업중앙회, 협회 등 포함 이직한 분들 계신지요   

                                                    text writer upload_date  \
101    현재 7학기 끝난 학생입니다 제가 사회 생활 경험이 거의 없기도 하고 생활비에도 보...     익명  2021-01-01   
550                                      맨날 집에만 있을 수도 없고     익명  2021-01-02   
1134   이번에 운좋게 채용전환인턴으로 근무를 시작하게되었습니다혹시 네일아트 화려하지나 23...     익명  2021-01-03   
1871                                  공공기관이나 교직원관련 경력없으면     익명  2021-01-04   
2347   안녕하세요,공사 취준 중 궁금한 점이 있어 글 남깁니다혹시, 공사 입사지원시 사기업...     익명  2021-01-05   
2412   원래 우리 부서는 재택근무를 권장하는 문화였어공공기관이라 13 재택근무 권장인데, ...     익명  2021-01-06   
2750   제가 만약 위대한 개츠비 아니면 데미안 같은 작품을리메이크하거나 웹툰으로 그린다고 ...     익명  2021-01-06   
3364   다음시즌에 정부가 공공일자리, 공무원도 제일 많이 뽑는다던데 지원자들이 거기로 좀 ...     익명  2021-01-08   
3496   조그마한 소도시 살고있는데 여기에서 일자리 창출 공모전이 있어서 동생이 지원했어  ...     익명  2021-01-08   
3606                                         우린 절대 안해 왤까     익명  2021-01-09   
3697                        기껏 대학들어왔더니 취업 박살났네 ㅋ어떻게 살라는겨     익명  2021-01-09   
3713   어지저찌해서 공대에 들어와서2학년까지 마쳤지만                  전공이...     익명  2021-01-09   
3739    제일 큰 희망사항은 몸이 편했으면 좋겠음 무조건 앉아서 일하는 직업이었으면 좋겠구...     익명  2021-01-09   
4400                                                신기하네     익명  2021-01-11   
4682   열두시부터 대기탔는데 결국 접수 못했네 존나 짜증난다 진짜공시나 공직 채용에서 한국...     익명  2021-01-

---

num board                             title  \
0      1082901   익게2                             해피뉴이어   
1      1082902   익게2                  2021년 새해복 많이받으세요   
2      1082903   익게2                            첫글은 내꼬   
3      1082905   익게2                          땡ㅎㅎㅎㅎㅎㅎㅎ   
4      1082906   익게2                 어디 카운트 다운 하는 곳 없냐   
...        ...   ...                               ...   
77975  1200285   익게2  아버지께서 칼럼 쓰셨는데 댓글 한 번씩만 달아줄 수 있을까   
77976  1200287   익게2                    프로포폴 하면 기분이 좋음   
77977  1200288   익게2                 취업 후기 쓰려는데 안올라간다ㅠ   
77978  1200291   익게2                     간떨어지는동거 보는 사람   
77979  1200293   익게2                       오타루 오마카세 후기   

                                                    text writer upload_date  \
0                                   2021년은 모두 행복한 한해가 되길     익명  2021-01-01   
1                                      모든 일이 잘 되기를 12시 땡     익명  2021-01-01   
2                                              예비회계사 나다미     익명  2021-01-01   
3                                                     1등     익명  2021-01-01   
4                                                   언제바껴     익명  2021-01-01   
...                                                  ...    ...         ...   
77975  2222408544049우리 아버지께서 이번에 짧은 칼럼처럼 블로그에 쓰시는 거 맡...     익명  2021-06-30   
77976                              하는거 신기하네하면 힙해보여서 하는건가     익명  2021-06-30   
77977  손다쳐서 폰으로 열심히 적었는데나한테왜 이래ㅠ혹시 뭔가 지켜야 하는 양식이 있나요ㅠ...     익명  2021-06-30   
77978  아 이번주 기대했는데                                예고편...     익명  2021-06-30   
77979  전에 어떤 다미가 추천한거 보고 오늘 가봤어ㅎㅎ디너 오마카세 가격은 55,000원이...     익명  2021-06-30   

      upload_time    view  likes  dislikes  \
0           00:00  1343.0  195.0       0.0   
1           00:00   107.0    3.0       0.0   
2           00:00   139.0    1.0       0.0   
3           00:00    39.0    0.0       0.0   
4           00:00    84.0    0.0       0.0   
...           ...     ...    ...       ...   
77975       23:43  5802.0  374.0      11.0   
77976       23:47   373.0    1.0       1.0   
77977       23:49   387.0    3.0       0.0   
77978       23:55   138.0    6.0       0.0   
77979       23:59   869.0   24.0       0.0   

                                                comments  \
0      앗, 성지다, 첫글 ㅊㅊ, 추천 준다, 내 24살은 인생에서 가장 빛나는 날로 만들...   
1                                                    늦었네   
2                                         ㄹㅇ 1등이네 ㅋㅋ, 실패   
3                                                          
4                                              232번 불교방송   
...                                                  ...   
77975  비댓으로 달래 너무 귀엽다, 이 글 조회수 늘리려면 제목 바꾸는거 추천 광고글인줄 ...   
77976  썰로 들은 거라 정확하지는 않는데 지방흡입할 때 고통 줄이려고 프로포폴 투약하다가 ...   
77977  중간에 임티 넣었었어, 임티, 1 이모티콘 빼기2 사진 많으면 업로드 될 동안 조금...   
77978  너무 오글거리는데 장기용때매 봄 ㅎㅎ, 난 계선우땜에 봐ㅠㅠ, 나도 계선우 때문에 ...   
77979  맛있겠다, 김을 안 주는게 아쉽다, 너무 괜찮은데 와 나도 가보고싶다지방다미, 와 ...   

                                         comments_writer  comments_cnt  \
0                                                                 20.0   
1                                       2빠다 ㅎㅎ, 내년에 도전한다           3.0   
2                                                     ㅜㅜ           3.0   
3                                                                  0.0   
4                                                                  1.0   
...                                                  ...           ...   
77975  헉 피드백 반영했어 너무 고마워, 엇 아마 확인은 못하실 텐데 비댓이든 공개댓이든 ...          75.0   
77976                                                              5.0   
77977                                              이건 되네           7.0   
77978                                                              3.0   
77979  존맛 꼭가봐ㅎㅎ, 아무래도 가격이 가격인지라 전반적으로 딱 기본에 충실한 느낌이긴 ...          16.0   

                                          text_tokenized  \
0      [(2021년, Number), (은, Foreign), (모두, Noun), (행...   
1      [(모든, Noun), (일이, Modifier), (잘, Verb), (되, Ve...   
2       [(예비, Noun), (

## ETC

In [962]:
Posts_mat = np.zeros((7,len(idx_extended)))
for i, key in enumerate(idx_extended):
    print(i)
    for j in range(1,7):
        print(j)
        Posts_mat[j,i] = numofposts(key,i)

0
1
2
3
4
5
6
1
1
2
3
4
5
6
2
1
2
3
4
5
6
3
1
2
3
4
5
6
4
1


KeyboardInterrupt: 

In [ ]:
with open('posts_mat.pkl','wb') as f:
    pickle.dump(Posts_mat,f)